#ifndef ROBOTMAP_H
#define ROBOTMAP_H


#define	PWM_DRIVE_LEFT_FRONT 0
#define	PWM_DRIVE_LEFT_CENTER_REAR 1
#define	PWM_DRIVE_RIGHT_FRONT 2
#define	PWM_DRIVE_RIGHT_CENTER_REAR 3

#define PWM_FRONT_PICKUP_LEFT_ARM 4
#define PWM_FRONT_PICKUP_RIGHT_ARM 5

#define PWM_BACK_PICKUP_BASE_MOTOR 6
#define PWM_BACK_PICKUP_ROLLERS 7

#define PWM_SHOOT_MOTOR 8

#define RELAY_FRONT_PICKUP_LEFT_ROLLERS 0
#define RELAY_FRONT_PICKUP_RIGHT_ROLLERS 1

#define	DI_DRIVE_RIGHT_A 0
#define	DI_DRIVE_RIGHT_B 1
#define	DI_DRIVE_LEFT_A 2
#define	DI_DRIVE_LEFT_B 3
#define DI_BALL_SHOOTER_SENSOR 5
#define DI_FRONT_PICKUP_BALL_SENSOR 4
#define DI_DRIVE_TAPE_SENSOR 6
#define DI_BACK_PICKUP_SENSOR 7

#define AI_GYRO 0
#define AI_FRONT_PICKUP_RIGHT_ARM_POT 1
#define AI_FRONT_PICKUP_LEFT_ARM_POT 2
#define AI_SHOOT_POT 3
#define AI_BACK_PICKUP_BASE_POT 4
#define AI_RANGEFINDER 5

#define SOLENOID_SENSOR_POWER1 0
#define SOLENOID_SENSOR_POWER2 1
#define SOLENOID_TAPE_DETECT   2

#endif
